"""
export.py — Download / handoff utilities
=========================================
Provides GeoJSON, CSV, and Revit handoff ZIP exports.
"""

from __future__ import annotations

import io
import json
import zipfile

import geopandas as gpd
import numpy as np
import pandas as pd


def _json_default(obj):
    """Serialise NumPy scalars for json.dumps."""
    if isinstance(obj, np.integer):
        return int(obj)
    if isinstance(obj, np.floating):
        return float(obj)
    if isinstance(obj, np.bool_):
        return bool(obj)
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    raise TypeError(f"Object of type {type(obj).__name__} is not JSON serializable")


def metrics_to_csv(metrics: dict) -> str:
    """Return a metrics dict as CSV bytes string."""
    clean = {k: v for k, v in metrics.items() if not k.startswith("_")}
    df = pd.DataFrame([clean])
    return df.to_csv(index=False)


def comparison_csv(metrics_a: dict, metrics_b: dict) -> str:
    """Return a side-by-side comparison CSV."""
    keys = [k for k in metrics_a if not k.startswith("_")]
    data = {
        "Metric": keys,
        "Proposal A": [metrics_a.get(k, "") for k in keys],
        "Proposal B": [metrics_b.get(k, "") for k in keys],
    }
    return pd.DataFrame(data).to_csv(index=False)


def geojson_download(gdf: gpd.GeoDataFrame) -> str:
    """Return GeoDataFrame as WGS84 GeoJSON string."""
    if gdf is None or gdf.empty:
        return json.dumps({"type": "FeatureCollection", "features": []})
    try:
        export = gdf.to_crs(epsg=4326)
    except Exception:
        export = gdf
    return export.to_json()


def revit_handoff_zip(
    gdf: gpd.GeoDataFrame | None,
    site_gdf: gpd.GeoDataFrame,
    metrics: dict,
    proposal_name: str = "Selected Proposal",
) -> bytes:
    """
    Build a structured Revit handoff ZIP.

    Contents
    --------
    buildings.csv, roads.csv, green_areas.csv,
    site.geojson, proposal_metrics.csv,
    proposal_summary.json, README.txt
    """
    buf = io.BytesIO()

    with zipfile.ZipFile(buf, "a", zipfile.ZIP_DEFLATED, False) as zf:

        # ── Geometry CSVs (only if GeoDataFrame is available) ────────────────
        if gdf is not None and not gdf.empty:
            for layer, label in [
                ("building", "buildings"),
                ("road", "roads"),
                ("green_space", "green_areas"),
            ]:
                subset = gdf[gdf["type"] == layer].copy()
                if not subset.empty:
                    subset["x"] = subset.geometry.centroid.x
                    subset["y"] = subset.geometry.centroid.y
                    cols = ["x", "y"]
                    if layer == "building":
                        for c in ["building_id", "footprint_area", "height", "floors", "use", "gfa"]:
                            if c in subset.columns:
                                cols = [c for c in ["building_id", "x", "y", "footprint_area", "height", "floors", "use", "gfa"] if c in subset.columns]
                                break
                    zf.writestr(f"revit_handoff/{label}.csv", subset[cols].to_csv(index=False))

        # ── Site GeoJSON ─────────────────────────────────────────────────────
        try:
            site_exp = site_gdf.to_crs(epsg=4326)
        except Exception:
            site_exp = site_gdf
        zf.writestr("revit_handoff/site.geojson", site_exp.to_json())

        # ── Proposal metrics CSV ──────────────────────────────────────────────
        zf.writestr("revit_handoff/proposal_metrics.csv", metrics_to_csv(metrics))

        # ── Proposal summary JSON ─────────────────────────────────────────────
        clean = {k: v for k, v in metrics.items() if k != "_sources"}
        zf.writestr(
            "revit_handoff/proposal_summary.json",
            json.dumps(clean, indent=2, default=_json_default),
        )

        # ── README ────────────────────────────────────────────────────────────
        readme = f"""URBANGRID – REVIT HANDOFF PACKAGE
====================================
Generated by UrbanGrid MVP | Smart India Hackathon 2026 (PS 26114)
Selected proposal: {proposal_name}

WORKFLOW
--------
1. Proposal created and analysed in Autodesk Forma Site Design
2. Proposal selected by UrbanGrid scoring engine
3. This package provides structured data for detailed BIM development in Autodesk Revit
4. Revit team develops individual buildings, MEP, and documentation
5. Final model synchronised back to Forma for site presentation

FILES
-----
buildings.csv      – building_id, x, y, footprint_area, height, floors, use, gfa
roads.csv          – road polygon centroids (x, y)
green_areas.csv    – green space polygon centroids (x, y)
site.geojson       – site boundary in WGS84
proposal_metrics.csv – full KPI snapshot
proposal_summary.json – structured summary for import

NOTE: This package does NOT auto-generate an RVT file.
      Use this data to set up your Revit project manually.
"""
        zf.writestr("revit_handoff/README.txt", readme)

    return buf.getvalue()
